# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weight', '0003_auto_20160416_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_oauth_code', models.CharField(max_length=200, null=True)),
                ('fitbit_authorization_token', models.CharField(max_length=200, null=True)),
                ('fitbit_refresh_token', models.CharField(max_length=200, null=True)),
                ('fitbit_scopes', models.TextField(null=True)),
                ('fitbit_token_type', models.CharField(max_length=128, null=True)),
                ('expiration_date', models.DateField(editable=False, null=True)),
                ('fitbit_user_id', models.DateField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
