# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_fitbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbit',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
