# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_auto_20180710_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbit',
            old_name='fitbit_authorization_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='fitbit',
            old_name='fitbit_oauth_code',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='fitbit',
            old_name='fitbit_scopes',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='fitbit',
            old_name='fitbit_token_type',
            new_name='token_type',
        ),
        migrations.RemoveField(
            model_name='fitbit',
            name='fitbit_refresh_token',
        ),
    ]
