# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0006_auto_20180710_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbit',
            name='expiration_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='fitbit_user_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
