# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0007_auto_20180710_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbit',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='fitbit_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitbit',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
