# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180702_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.ForeignKey(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author', to_field='name', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.ForeignKey(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author', to_field='name', verbose_name='Author'),
        ),
    ]
