# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180702_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_user_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
