# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-06 12:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180705_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_language',
            field=models.ForeignKey(default=2, help_text='Language to use when sending you email notifications, e.g. email reminders for workouts. This does not affect the language used on the website.', on_delete=django.db.models.deletion.CASCADE, to='core.Language', verbose_name='Notification language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_english_ingredients',
            field=models.BooleanField(default=True, help_text='Check to also show ingredients in English while creating\na nutritional plan. These ingredients are extracted from a list provided\nby the US Department of Agriculture. It is extremely complete, with around\n7000 entries, but can be somewhat overwhelming and make the search difficult.\n', verbose_name='Also use ingredients in English'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_duration',
            field=models.IntegerField(default=12, help_text='Default duration in weeks of workouts not in a schedule. Used for email workout reminders.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Default duration of workouts'),
        ),
    ]
