# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20180706_1516'),
        ('manager', '0009_auto_20180710_1545'),
    ]

    operations = [
    ]
